language: ruby
rvm:
- 2.1
script:
- npm install
- grunt test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: informatics-blog
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  on:
    branch: master
after_deploy:
  - grunt purge
notifications:
  webhooks:
    urls:
      - $NOTIFICATION_WEBHOOK
    on_success: always 
    on_failure: always 
    on_start: never   
    on_cancel: never 
    on_error: always
